table Dim_Date
	lineageTag: 614e1645-7325-4fab-bfc6-f235ad11a368

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cbca5ece-55f6-467a-bcdc-2ea142c0a119
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f654a917-5aee-488b-91a3-20539e1bf750
			defaultHierarchy: LocalDateTable_b0531550-11d4-4d43-88f3-c1d9a99481da.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 54abb183-bb33-4ea7-b989-4b3fb8ecb4c9
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Month
		dataType: int64
		formatString: 0
		lineageTag: e0a8f392-7a8e-47c2-8a65-8fad04153f32
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 37b83d32-4406-41df-af74-1f0218c246d5
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 95f9a178-4802-4724-826b-2db712f846ab
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Fact_Sales,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"sale_id", "store_format", "category", "item", "quantity", "city", "unit_price", "sales_amount"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Inserted Year" = Table.AddColumn(#"Removed Duplicates", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Month Name", "Day", each Date.Day([date]), Int64.Type)
				in
				    #"Inserted Day"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

